# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login1.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from PyQt5.QtGui import *

import main #导入主窗体
from service import service
from PyQt5.QtWidgets import *


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 270, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(230, 330, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(250, 50, 361, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.editUser = QtWidgets.QLineEdit(self.centralwidget)
        self.editUser.setGeometry(QtCore.QRect(360, 280, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.editUser.setFont(font)
        self.editUser.setObjectName("editUser")
        self.editPwd = QtWidgets.QLineEdit(self.centralwidget)
        self.editPwd.setGeometry(QtCore.QRect(360, 330, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.editPwd.setFont(font)
        self.editPwd.setObjectName("editPwd")
        #将密码设置为暗码
        self.editPwd.setEchoMode(QtWidgets.QLineEdit.Password)

        self.btnLogin = QtWidgets.QPushButton(self.centralwidget)
        self.btnLogin.setGeometry(QtCore.QRect(250, 420, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnLogin.setFont(font)
        self.btnLogin.setObjectName("btnLogin")
        self.btnQuit = QtWidgets.QPushButton(self.centralwidget)
        self.btnQuit.setGeometry(QtCore.QRect(400, 420, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnQuit.setFont(font)
        self.btnQuit.setObjectName("btnQuit")
        LoginWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LoginWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 33))
        self.menubar.setObjectName("menubar")
        LoginWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LoginWindow)
        self.statusbar.setObjectName("statusbar")
        LoginWindow.setStatusBar(self.statusbar)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

        #给窗体添加背景
        #设置窗体的背景
        palette = QtGui.QPalette()
        palette.setBrush(MainWindow.backgroundRole(),
                         QBrush(QPixmap('./img/img.png')
                                .scaled(MainWindow.size(),
                                        QtCore.Qt.IgnoreAspectRatio,
                                        QtCore.Qt.SmoothTransformation)))
        MainWindow.setPalette(palette)
        #设置自动填充背景
        MainWindow.setAutoFillBackground(True)

        #为登录按钮绑定槽函数，
        self.btnLogin.clicked.connect(self.openMain)
        #为密码框关联槽函数
        #密码写完之后 回车 执行槽函数
        self.editPwd.editingFinished.connect(self.openMain)

    #定义槽函数,用于打开主窗体
    def openMain(self):#
        #登录成功后打开主窗体
        #获取登录的用户名
        service.user_name = self.editUser.text()
        self.user_pwd = self.editPwd.text()#用于获取密码

        # 判断用户名和密码是否正确
        # 判断是否为空
        if service.user_name != '' and self.user_pwd != '':
            #到数据库中执行查询操作
            sql='select * from tb_user where userName=%s and userPwd=%s'
            #result是一个元组类型
            result=service.query(sql,service.user_name,self.user_pwd)
            if len(result) > 0:  # 计算元组中元素的个数
                self.m=main.Ui_MainWindow()  # 创建主窗体对象
                self.m.show()
                # 隐藏登录窗口
                MainWindow.hide()
            else:
                self.editUser.setText('')
                self.editPwd.setText('')
                QMessageBox.warning(None, '警告', '请输入正确的用户名和密码！！', QMessageBox.Ok)
        else:
            QMessageBox.warning(None,'警告','用户名或密码不能为空！！', QMessageBox.Ok)

    def retranslateUi (self, LoginWindow ):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "系统登录"))
        self.label.setText(_translate("LoginWindow", "用户名："))
        self.label_2.setText(_translate("LoginWindow", "密  码："))
        self.label_3.setText(_translate("LoginWindow", "学生成绩管理系统"))
        self.btnLogin.setText(_translate("LoginWindow", "登录"))
        self.btnQuit.setText(_translate("LoginWindow", "退出"))

if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()  # 创建窗体的对象
    #  创建pyqt5创建的窗体对象
    ui = Ui_LoginWindow()
    #  调用pyqt5窗体对象的方法，对窗体对象进行初始化设置
    ui.setupUi(MainWindow)
    MainWindow.show()  # 显示窗体
    sys.exit(app.exec_())  # 程序关闭时退出进程




