# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QBrush, QPixmap
from PyQt5.QtWidgets import *
#导入主窗体可以打开的子窗体
from settings import grade,classes,subject,examkinds
from baseinfo import student,result
from query import studentinfo,resultinfo
from system import *

class Ui_MainWindow(QMainWindow):
    def __init__(self):
        super(Ui_MainWindow,self).__init__()
        #主窗体不允许最大化
        self.setWindowFlags(QtCore.Qt.MSWindowsFixedSizeDialogHint)
        self.setupUi(self)
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 33))
        self.menubar.setObjectName("menubar")
        self.menuji = QtWidgets.QMenu(self.menubar)
        self.menuji.setObjectName("menuji")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionGrade = QtWidgets.QAction(MainWindow)
        self.actionGrade.setObjectName("actionGrade")
        self.actionClass = QtWidgets.QAction(MainWindow)
        self.actionClass.setObjectName("actionClass")
        self.actionExamKind = QtWidgets.QAction(MainWindow)
        self.actionExamKind.setObjectName("actionExamKind")
        self.actionSubject = QtWidgets.QAction(MainWindow)
        self.actionSubject.setObjectName("actionSubject")
        self.actionStudent = QtWidgets.QAction(MainWindow)
        self.actionStudent.setObjectName("actionStudent")
        self.actionResult = QtWidgets.QAction(MainWindow)
        self.actionResult.setObjectName("actionResult")
        self.actionStudentInfo = QtWidgets.QAction(MainWindow)
        self.actionStudentInfo.setObjectName("actionStudentInfo")
        self.actionResultInfo = QtWidgets.QAction(MainWindow)
        self.actionResultInfo.setObjectName("actionResultInfo")
        self.actionUser = QtWidgets.QAction(MainWindow)
        self.actionUser.setObjectName("actionUser")
        self.menuji.addAction(self.actionGrade)
        self.menuji.addAction(self.actionClass)
        self.menuji.addAction(self.actionExamKind)
        self.menuji.addAction(self.actionSubject)
        self.menu.addAction(self.actionStudent)
        self.menu.addAction(self.actionResult)
        self.menu_2.addAction(self.actionStudentInfo)
        self.menu_2.addAction(self.actionResultInfo)
        self.menu_3.addAction(self.actionUser)
        self.menubar.addAction(self.menuji.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # 给窗体添加背景
        # 设置窗体的背景
        palette = QtGui.QPalette()
        palette.setBrush(MainWindow.backgroundRole(),
                         QBrush(QPixmap('./img/img_1.png')
                                .scaled(MainWindow.size(),
                                        QtCore.Qt.IgnoreAspectRatio,
                                        QtCore.Qt.SmoothTransformation)))
        MainWindow.setPalette(palette)
        # 设置自动填充背景
        MainWindow.setAutoFillBackground(True)

        #为子菜单项绑定关联函数
        self.menubar.triggered[QtWidgets.QAction].connect(self.openSet)

    # 在主窗体编写自定义槽函数
    def openSet (self, m):
        # 打开对应的子窗体
        if m.text()=='年级设置':
            self.m=grade.Ui_MainWindow()
            self.m.show()
        elif m.text()=='班级设置':
            self.m=classes.Ui_MainWindow()
            self.m.show()
        elif m.text()=='考试类别':
            self.m=examkinds.Ui_MainWindow()
            self.m.show()
        elif m.text()=='考试科目设置':
            self.m=subject.Ui_MainWindow()
            self.m.show()
        elif m.text()=='学生信息管理':
            self.m=student.Ui_MainWindow()
            self.m.show()
        elif m.text()=='学生成绩管理':
            self.m=result.Ui_MainWindow()
            self.m.show()
        elif m.text()=='学生信息查询':
            self.m=studentinfo.Ui_MainWindow()
            self.m.show()
        elif m.text()=='成绩信息查询':
            self.m = resultinfo.Ui_MainWindow()
            self.m.show()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "学生成绩管理系统"))
        self.menuji.setTitle(_translate("MainWindow", "基础设置"))
        self.menu.setTitle(_translate("MainWindow", "基本信息管理"))
        self.menu_2.setTitle(_translate("MainWindow", "系统查询"))
        self.menu_3.setTitle(_translate("MainWindow", "系统管理"))
        self.actionGrade.setText(_translate("MainWindow", "年级设置"))
        self.actionClass.setText(_translate("MainWindow", "班级设置"))
        self.actionExamKind.setText(_translate("MainWindow", "考试类别"))
        self.actionSubject.setText(_translate("MainWindow", "考试科目设置"))
        self.actionStudent.setText(_translate("MainWindow", "学生信息管理"))
        self.actionResult.setText(_translate("MainWindow", "学生成绩管理"))
        self.actionStudentInfo.setText(_translate("MainWindow", "学生信息查询"))
        self.actionResultInfo.setText(_translate("MainWindow", "成绩信息查询"))
        self.actionUser.setText(_translate("MainWindow", "用户维护"))
