# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'studentinfo.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *

import sys
sys.path.append('../')#为什么，因为grade.py与需要先从当前路径出来，再进入service中
from service import service

class Ui_MainWindow(QMainWindow):
    def __init__(self):
        super(Ui_MainWindow,self).__init__()
        #调用本类中的实例方法
        self.setupUi(self)
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 459)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cboQuery = QtWidgets.QComboBox(self.centralwidget)
        self.cboQuery.setGeometry(QtCore.QRect(160, 20, 111, 41))
        self.cboQuery.setObjectName("cboQuery")
        #添加下拉列表框
        self.cboQuery.addItem("学生编号")
        self.cboQuery.addItem("学生姓名")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 140, 41))
        self.label.setObjectName("label")
        self.editKey = QtWidgets.QLineEdit(self.centralwidget)
        self.editKey.setGeometry(QtCore.QRect(440, 20, 113, 41))
        self.editKey.setObjectName("editKey")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(300, 20, 140, 41))
        self.label_1.setObjectName("label_1")
        self.btnQuit = QtWidgets.QPushButton(self.centralwidget)
        self.btnQuit.setGeometry(QtCore.QRect(690, 20, 81, 31))
        self.btnQuit.setObjectName("btnQuit")
        self.btnQuery = QtWidgets.QPushButton(self.centralwidget)
        self.btnQuery.setGeometry(QtCore.QRect(590, 20, 81, 31))
        self.btnQuery.setObjectName("btnQuery")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 70, 761, 311))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 33))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.query()
        self.btnQuery.clicked.connect(self.query)
        self.btnQuit.clicked.connect(self.close)
    #自定义槽函数
    def query(self):
        self.tableWidget.setRowCount(0)#清空表格中的行
        #获取学生查询关键字
        if self.editKey.text() == "":#查询全部内容
            result=service.query('select stuid,stuname,concat(gradeName,className),age,sex,phone,address from v_studentinfo')
        else:#根据查询列表中的选项进行查询
            key=self.editKey.text()
            if self.cboQuery.currentText()=='学生编号':
                result = service.query(
                    'select stuid,stuname,concat(gradeName,className),age,sex,phone,address from v_studentinfo where stuid like %s',
                    '%' + key + '%')

            elif self.cboQuery.currentText()=='学生姓名':
                result = service.query(
                    'select stuid,stuname,concat(gradeName,className),age,sex,phone,address from v_studentinfo where stuname like %s',
                    '%' + key + '%')
        row=len(result)
        self.tableWidget.setRowCount(row)#设置表格的行数
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setHorizontalHeaderLabels(
            ['学生编号','学生姓名','班级','年龄','性别','电话','地址']
        )
        for i in range(row):
            for j in range(7):
                data=QTableWidgetItem(str(result[i][j]))
                self.tableWidget.setItem(i, j, data)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "学生信息查询"))
        self.label.setText(_translate("MainWindow", "选择查询列表："))
        self.label_1.setText(_translate("MainWindow", "输入查询关键字："))
        self.btnQuit.setText(_translate("MainWindow", "退出"))
        self.btnQuery.setText(_translate("MainWindow", "查询"))
